### ISSUE TITLE
http://[ipv4 ip address]:[port]/[path] are not correctly recognised

### ISSUE THREAD

**Issue by davibe** [kevva/url-regex#14]
i.e.

    > asd = require('url-regexp')
    { validate: [Function], match: [Function] }
    > asd.match('http://192.168.1.1:1234/foo')
    []
    > asd.match('http://192.168.1.12:1234/foo')
    []
    > asd.match('http://123.123.123.123:1234/foo')
    [ 'http://123.123.123.12' ]
    > wtf?

**Comment by shinnn** [comment]
That's [url-regexp](https://github.com/gajus/url-regexp) issue. Please check the repository name carefully before opening new issues.

**Comment by davibe** [comment]
Ok, thank you
