### ISSUE TITLE
Match URLs that start with 'www.'

### ISSUE THREAD

**Issue by simonvizzini** [kevva/url-regex#17]
First thing I noticed with this regex is that it doesn't match URLs that start with a 'www', and now I'm wondering if there was a reason why this was not included yet. Were there maybe some kind of issues? I've patched the regex to also match URLs that start with www (and also optional digits after the www, for URLs like www2.blah.com), and haven't noticed any issues yet.

So, was there a reason why the regex shouldn't match such URLs? If not then I'll gladly create a pull request for my patch. Let me know, thanks!

**Comment by panganibanpj** [comment]
There's a [similar issue](https://github.com/sindresorhus/get-urls/issues/10) in get-urls (which depends on this) that the authors commented on
