### ISSUE TITLE
Don't match URL that contains \s

### ISSUE THREAD

**Issue by Reon90** [kevva/url-regex#22]
Example http://6 6.6.6.6

**Comment by kevva** [comment]
Why? That isn't a valid URL.

**Comment by Reon90** [comment]
Sorry, i corrected the title.
Your regexp thinks that this 'http://6 6.6.6.6' is the correct URL

**Comment by radiovisual** [comment]
@Reon90 , This module already doesn't match on URLs that contains spaces (`\s`)'s, so this issue can be closed.

In my tests, the url `'http://6 6.6.6.6'` is not considered a valid url by this module (because it contains a space after the protocol):

```js
var urlRegExp = require("url-regex");

var url = 'http://6 6.6.6.6';

urlRegExp().test(url);
//=> false

urlRegExp({exact: true}).test(url);
//=> false
```
