### ISSUE TITLE
duplicate test entry (should be unique test case?)

### ISSUE THREAD

**Issue by radiovisual** [kevva/url-regex#25]
[Line 52 in test.js](https://github.com/kevva/url-regex/blob/master/test.js#L51) shows a duplicate test case:

```js
		'ws://foo.ws',
		'ws://foo.ws',
```
 is this a typo, or was it meant be two different tests, for example:

```js
		'ws://foo.ws',
		'ws://foo.ws/rainbows',
```
I just wanted to point this out in case the duplicate was meant to be an important test case that was left out.

**Comment by kevva** [comment]
Just a mistake.
