### ISSUE TITLE
Can't build v4 using browserify

### ISSUE THREAD

**Issue by jimhigson** [kevva/url-regex#29]
Hi,

v4.0.0 doesn't build using browserify in some configurations because browserify doesn't apply transforms to node_modules by default. This means that a fairly typical browserify/babel/uglify chain won't work.

This problem goes away if we add this to the url-regex package.json, so that browserify knows to transpile this module:

```
    "browserify": {
        "transform": [
            [
                "babelify",
                {
                    "presets": "es2015"
                }
            ]
        ]
    }
```

Let me know and I can make a pull request for the above.

**Comment by sindresorhus** [comment]
https://github.com/kevva/url-regex/pull/30#issuecomment-261157321
