### ISSUE TITLE
options to check for protocol-less URLs w/ TLD whitelist

### ISSUE THREAD

**Issue by jonathanong** [kevva/url-regex#31]
i was hoping `exact` would be the option i need based on https://github.com/kevva/url-regex/issues/12#issuecomment-97568552, but i don't think you guys have revisited this.

what's the possibility of this? would using https://github.com/stephenmathieson/node-tlds as a whitelist not be sufficient?

**Comment by kevva** [comment]
I removed that in https://github.com/kevva/url-regex/commit/c01d9628c751ddd595989280c274eb758a62975a.

**Comment by jonathanong** [comment]
yes i know you removed it. my question is whether you guys have rediscussed this per the comment above. i'd rather not fork this repo for this feature.

**Comment by matthewmueller** [comment]
+1 sort of thought this library would handle this

**Comment by matthewmueller** [comment]
fwiw, pulled the regex out of https://github.com/segmentio/is-human-url

**Comment by kevva** [comment]
I'm considering adding this, though I need a better option name than `strict`. It's too similar to `exact`.
