### ISSUE TITLE
4.0.0 also broke Safari

### ISSUE THREAD

**Issue by darobin** [kevva/url-regex#33]
The v4 upgrade that switched to ES2015 broke Safari (it will throw errors indicating that it does not support `const` in strict mode, then give up). By default browserify+babelify does not transpile dependencies, so `url-regex` is being included as is. (That also breaks UglifyJS as it doesn't do ES2015 yet.)

Reverting to 3.2 fixes the problem. I don't know if you want to back out of this change to keep supporting Safari, or if you'd rather wait it out (or provide a `client` transpiled version). If you prefer to wait it out it might be helpful to point the issue out in the README.

**Comment by SamVerschueren** [comment]
If you want support for browsers, use 3.2 like you mentioned. Module maintainers shouldn't be forced to use ES5 because of browser support, it should be handled by module bundlers imo.
