### ISSUE TITLE
Avoid matching ) after a slash at end of url

### ISSUE THREAD

**Issue by averissimo** [kevva/url-regex#34]
Example:

`[and another](https://another.example.com/) and`

![image](https://cloud.githubusercontent.com/assets/211358/22739760/65b9a1a6-ee0d-11e6-8b70-9270c4f0ee92.png)

first asked for in: https://github.com/yakyak/yakyak/pull/578

**Comment by alebelcor** [comment]
I was just about to report the same issue.

[Here's quick test using RunKit](https://runkit.com/58b8caf6099e360015589b44/58c492833ea1e600131d12ba).

**Comment by averissimo** [comment]
Yay!! looking forward to get it merged

**Comment by davibe** [comment]
@kevva will you merge this ? we are waiting for it https://github.com/yakyak/yakyak/pull/578

**Comment by kevva** [comment]
See https://github.com/kevva/url-regex/pull/35#issuecomment-302936342.

**Comment by sampsyo** [comment]
FWIW the same issue exists with another Markdown convention: angle brackets for linked URLs.

```
> '<http://example.com>'.match(urlRegex())
[ 'http://example.com' ]
> '<http://example.com/>'.match(urlRegex())
[ 'http://example.com/>' ]
```
