### ISSUE TITLE
Avoid matching period at the end of url

### ISSUE THREAD

**Issue by hnordt** [kevva/url-regex#36]
An URL that ends with a period ("http://google.com.") would match. This isn't a huge deal but could cause some issues.

It might be related to https://github.com/kevva/url-regex/issues/34.

**Comment by kevva** [comment]
https://github.com/kevva/url-regex/issues/23#issuecomment-230365867

**Comment by niftylettuce** [comment]
This is fixed in `url-regex-safe` v1.0.0 at https://github.com/niftylettuce/url-regex-safe.

Feel free to use this as a replacement!
