### ISSUE TITLE
match(urlRegex({strict:false})) returns urls with TLDs truncated to 2 characters

### ISSUE THREAD

**Issue by andyford** [kevva/url-regex#41]
Here's a runkit example https://runkit.com/593fd473d55e110011acb04c/593fd473d55e110011acb04d

By not being strict, I can understand why this might be the case.  Might there be another way to test in a non-strict way but have the full urls in the output array?

**Comment by kevva** [comment]
Ok, we need to sort the TLDs by `length` first I think.

**Comment by kevva** [comment]
Should be fixed now. Try reinstalling and test again :).

**Comment by andyford** [comment]
Wow! Thank you! Version 4.1.1 now works as expected in our implementation as well as on runkit (https://runkit.com/593fd473d55e110011acb04c/593fe3b72f088700156959d0)

Many thanks @kevva !
