### ISSUE TITLE
package not transpiled

### ISSUE THREAD

**Issue by tknuts** [kevva/url-regex#44]
Please create a transpiled version of package, hat to add the following to my webpack.config.js

      rules: [{
        // Temp fix, because they have not transpiled it them selfs
        test: /index\.js?$/i,
        include: /url-regex/,
        use: ['babel-loader?cacheDirectory']
      }, 

In order for my UglifyJsPlugin to complete without errors...

**Comment by kevva** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here sindresorhus/ama#446.

If you use Webpack, check out [babel-engine-plugin](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
