### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by mgresak** [kevva/url-regex#46]
When building an angular 2 app for production using `ng build --prod`, build fails with this message:

> ERROR in vendor.8a7e2466f2b7f474b403.bundle.js from UglifyJs
Unexpected token: operator (>) [/Users/user/Documents/git projects/angular-project/node_modules/url-regex/index.js:4,0][vendor.8a7e2466f2b7f474b403.bundle.js:888,23]

However, development server starts page successfully by using `npm start`.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled. Or install an older version of this module which targets Node.js 0.10.

**Comment by mgresak** [comment]
> Or install an older version of this module which targets Node.js 0.10.

Thanks @SamVerschueren. What version should I aim for?

**Comment by SamVerschueren** [comment]
3.2.0 should do https://github.com/kevva/url-regex/commits/master
