### ISSUE TITLE
Shortened URL's are not matched

### ISSUE THREAD

**Issue by rajeevdesai** [kevva/url-regex#52]
Shortened urls like `goo.gl/l45ry5` are not matched.

**Comment by KiranShakya** [comment]
@rajeevdesai This issue couldn't be reproduced. Please check if it is still reproducible.

**Comment by finoramic** [comment]
@KiranShakya I agree, this issue is resolved now by using `strict: false` option. You can close this now.

**Comment by rajeevdesai** [comment]
@KiranShakya I agree, this issue is resolved now by using `strict: false` option. I'm closing this now.
